Math Change
arksap2002/int-increase pull request #15
Opened 2019-09-07 19:32 UTC by arksap2002

2019-09-08 09:46 UTC, arksap2002 commented
Здесь будут только числа и всевозможные вложности друг в друга Math операций. Обрабатывание операций с именами будет в другой ветке.

2019-09-08 09:56 UTC, arksap2002 commented
Еще не доделал

2019-09-11 17:56 UTC, arksap2002 commented
Нужна ветка Test Run

2019-09-11 19:24 UTC, yeputons requested changes

2019-09-11 19:24 UTC, yeputons commented on src/main/java/TransformVisitor.java
> +        if (n.getArguments().get(0).isIntegerLiteralExpr()) {
Не надо это разбирать. Аргумент — это произвольное арифметическое выражение. А для произвольных арифметических выражений код уже написан.

Тут должно быть строчек 5-10, не больше. И ноль ифов.

2019-09-13 19:22 UTC, yeputons requested changes

2019-09-13 19:22 UTC, yeputons commented on src/main/java/TransformVisitor.java
> +        for (int i = 0; i < 2; i++) {
Убрать цикл `for`, код получится сильно короче

2019-09-27 19:10 UTC, yeputons requested changes

2019-09-27 19:10 UTC, yeputons commented on src/main/java/Replacing.java
> +            if (isMath(resolvedN) && resolvedN.getName().equals("min")) {
Проверить, что параметры — типа `int`. Аналогично с `abs` и `max`

2019-09-27 19:10 UTC, yeputons commented on src/main/java/Replacing.java
> +    private void mathMinOrMaxChanging(final String string,
Пока нафиг, слишком маленький и специфичный.

2019-09-27 19:10 UTC, yeputons commented on src/test/java/BigIntegerReplaceTest.java
> +    public void testMathFromImport() throws IOException, ClassNotFoundException {
Пофиксить порядок тест.

2019-09-27 19:10 UTC, yeputons commented on src/test/resources/MathWithClass.before.java
> +public class MathWithClass {
Добавить в тесты.

2019-09-30 19:16 UTC, yeputons requested changes

2019-09-30 19:16 UTC, yeputons commented on src/main/java/Replacing.java
> +                        getArguments().get(0))) {
Одно и то же условие повторяется дважды

2019-09-30 19:16 UTC, yeputons commented on src/main/java/Replacing.java
> +    private boolean checkingArgumentForInt(final Expression n) {
`isOfTypeInt`

2019-09-30 19:16 UTC, yeputons commented on src/main/java/Replacing.java
> +            return true;
Категорически не катит. Должно работать для любых выражений, которые имеют тип `int`. Добавь тест:

```
int x = Math.abs(2 + 2);
```

Надо узнавать тип `Expression` напрямую, а не разбирать, что это переменные/поля.

2019-09-30 19:20 UTC, yeputons requested changes

2019-09-30 19:20 UTC, yeputons commented on src/main/java/Replacing.java
> +            return true;
И добавь тест, в котором этот `return true;` оказывается неверным.

2019-09-30 19:23 UTC, yeputons commented on src/main/java/Replacing.java
> +            return true;
`JavaParserFacade.getType(Node)`

2019-10-03 18:22 UTC, arksap2002 commented
probablePrime ()
nextProbablePrime ()
divideAndRemainder
pow (^)
gcd ---
signum (comparison with 0)
shiftLeft (<<)
shiftRight (>>)
and (&)
or (|)
xor
not
compareTo (in variables) 
equals
toString
методы
-|-.print() / println()
Scanner / BuffRead
проверка на замену нужных int
посмотреть на for
long / short / byte
массивы??
++ / +=

2019-10-07 19:27 UTC, yeputons approved these changes

2019-10-07 19:27 UTC, merged