ToString
arksap2002/int-increase pull request #16
Opened 2019-09-07 22:50 UTC by arksap2002

2019-09-11 19:25 UTC, yeputons requested changes

2019-09-11 19:25 UTC, yeputons commented on src/main/java/TransformVisitor.java
> +        if (n.getArgument(0).isIntegerLiteralExpr()) {
Должно быть ноль ифов. Аналогично #15

2019-09-29 19:28 UTC, arksap2002 commented
Будет работать после обновления структуры

2019-10-08 15:18 UTC, arksap2002 commented
ToString редко бывает у переменной BigInteger. Он заработает, когда появится обрабатывания других переменных

2019-10-09 19:12 UTC, yeputons requested changes

2019-10-09 19:12 UTC, yeputons commented on src/test/java/BigIntegerReplaceTest.java
> +    public void testToStringChanging() throws IOException, ClassNotFoundException {
Что-то не то с порядком тестов.

2019-10-13 10:20 UTC, closed without merging