Parse Change
arksap2002/int-increase pull request #17
Opened 2019-09-09 18:57 UTC by arksap2002

2019-09-09 18:59 UTC, arksap2002 commented
я не доделал :(

2019-09-11 19:32 UTC, yeputons requested changes

2019-09-11 19:32 UTC, yeputons commented on src/main/java/TransformVisitor.java
> +                    n.getArguments()));
Надо убедиться, что аргументы у `ResolvedMethod` такие, какие ожидаем

2019-09-11 19:32 UTC, yeputons commented on src/main/java/TransformVisitor.java
> +            n.setType(bigIntegerType);
Это изменение — в отдельный PR

2019-09-11 19:32 UTC, yeputons commented on src/main/java/TransformVisitor.java
> +            }
Более правильный фикс: расширить концепцию "сначала смотрим на код и составляем план, а потом меняем" с методов на вообще все замены.

2019-09-13 19:19 UTC, yeputons approved these changes

2019-09-27 19:12 UTC, yeputons requested changes

2019-09-27 19:12 UTC, yeputons commented on src/test/java/BigIntegerReplaceTest.java
> +    public void testScannerFromImport() throws IOException, ClassNotFoundException {
Привести в порядок тесты — этих изменений быть не должно.

2019-09-30 19:24 UTC, yeputons approved these changes

2019-10-02 17:39 UTC, merged