Commit
arksap2002/int-increase pull request #2
Opened 2019-08-08 13:26 UTC by arksap2002

2019-08-08 18:02 UTC, yeputons requested changes

2019-08-08 18:02 UTC, yeputons commented on src/main/java/BigIntegerReplace.java
> +    public String firstTransform(final String string) throws IOException {
Должен быть один метод `transform`, который мы постепенно будем наращивать.

2019-08-08 18:02 UTC, yeputons commented on src/main/java/BigIntegerReplace.java
>      public String transform(final String string) throws IOException {
Кажется, `IOException` этот метод выкинуть но может, надо убрать. Вообще это должно было быть наблюдение в #1, но я пропустил.

2019-08-08 18:02 UTC, yeputons commented on src/main/java/BigIntegerReplace.java
> +    static class Finding extends VoidVisitorAdapter<JavaParserFacade> {
`Finding` --> `TransformVisitor`

2019-08-08 18:02 UTC, yeputons commented on src/main/java/BigIntegerReplace.java
> +                    simpleName.setIdentifier("BigInteger");
Если у пользователя есть свой класс `BigInteger` или нет импорта, случится беда. Давай тут fully qualified name (чтобы с импортами не возиться).

2019-08-08 18:02 UTC, yeputons commented on src/main/java/BigIntegerReplace.java
> +                simpleName.setIdentifier("nextBigInteger");
Эта замена - отдельное преобразование, должно идти в отдельном pull request.

2019-08-08 18:02 UTC, yeputons commented on src/test/java/BigIntegerReplaceTest.java
> +    public void testFirstTransform() throws IOException {
`testReplaceVariableDeclarationType`

2019-08-08 18:02 UTC, yeputons commented on src/test/resources/IntToBigInteger.after.java
> +        Scanner in = new Scanner(System.in);
Тесты сейчас надо делать микроскопические: проверяется _только_ корректная замена `int` на `BigInteger` в объявлениях переменных и ничего больше. Ну, проверяется, что не заменяется `long` и `String`, а также что не происходит замены в полях/аргументах методов.

Но это должен быть максимально простой пример, лучше искуственный. Никаких лишних импортов, `Scanner`, ввода-вывода, даже необязательно, чтобы программа что-то содержательное делала или чтобы все строчки выполнялись.

Чисто визуальные проверки. Содержательные будем добавлять потом.

2019-08-08 18:02 UTC, yeputons commented on src/test/java/BigIntegerReplaceTest.java
> +        assertEquals(IOUtils.resourceToString("/IntToBigInteger.after.java", Charset.defaultCharset()), gotOutput);
Так как тест надо будет сделать очень маленьким, название сменится с `IntToBigInteger` на что-то, в точности соответствующее названию метода для теста.

2019-08-08 18:02 UTC, yeputons commented on src/main/java/BigIntegerReplace.java
> +                new CombinedTypeSolver(new ReflectionTypeSolver());
Кажется. должно хватать просто `ReflectionTypeSolver`?

2019-08-08 18:50 UTC, arksap2002 commented on src/main/java/BigIntegerReplace.java
> +    public String firstTransform(final String string) throws IOException {
тогда не будет проходить первый тест (с foo)

2019-08-09 10:02 UTC, yeputons requested changes

2019-08-09 10:02 UTC, yeputons commented on src/main/java/BigIntegerReplace.java
> +                    simpleName.setIdentifier("java");
У `SimpleName` есть конструктор, который сразу поставит `Identifier`:

`new SimpleName("Java")`.

Это позволит избавиться от этой переменной и аналогичных.

2019-08-09 10:02 UTC, yeputons commented on src/main/java/BigIntegerReplace.java
> +                    classOrInterfaceType3.setName(simpleName);
У `ClassOrInterfaceType` аналогично: есть конструктор, который создаётся и сразу ставит себе `name` (и даже есть версия, которая и `SimpleName` создаёт за тебя), есть конструктор, который ставит и `name`, и `scope`. Так что тут можно от всех переменных избавиться и просто повызывать конструкторов в правильном порядке.

2019-08-09 10:02 UTC, yeputons commented on src/test/java/BigIntegerReplaceTest.java
> +    private void runTestFromFile(String string) throws IOException {
Всё так. Только `string` --> `filePrefix`. И лучше `/` добавлять не внутри `runTestFromFile`, а при вызове: тогда будет чуть "традиционнее" разделение ответственности: вызывающий передал почти полный путь, а функция дописала интересных расширений.

2019-08-09 10:02 UTC, yeputons commented on src/test/java/BigIntegerReplaceTest.java
>      public void testTransform() throws IOException {
`testTransform` --> `testNothingChanges`

2019-08-09 10:02 UTC, yeputons commented on src/test/java/BigIntegerReplaceTest.java
> +        runTestFromFile("Foo");
Переименуй файлы так, чтобы название соответствовало названию теста (`NothingChanges`)

2019-08-09 10:02 UTC, yeputons commented on src/test/java/BigIntegerReplaceTest.java
> +        runTestFromFile("OnlyTypeChanging");
Переименуй файлы так, чтобы соответствовало названию теста (`ReplaceVariableDeclarationType`)

2019-08-09 10:02 UTC, yeputons commented on src/test/resources/OnlyTypeChanging.before.java
> +import java.math.BigInteger;
Импорт лучше убрать, иначе можно случайно не протестировать, что добавляется `BigInteger` по полному имени.

2019-08-09 10:02 UTC, yeputons commented on src/test/resources/OnlyTypeChanging.before.java
> +
Пустые строчки лесом.

2019-08-09 10:02 UTC, yeputons commented on src/test/resources/OnlyTypeChanging.before.java
> +    int c = 100;
Это в точности совпадает с `int a = 100` по смыслу, лесом.
А лучше - сделать объявление нескольких переменных сразу, причём некоторых - без инициализаторов.

2019-08-09 10:02 UTC, yeputons commented on src/test/resources/OnlyTypeChanging.before.java
> +}
И добавь тут какой-нибудь метод с локальными переменными, чтобы проверить, что они тоже заменяются (а не только поля).

2019-08-09 21:15 UTC, arksap2002 commented on src/main/java/BigIntegerReplace.java
> +                    classOrInterfaceType3.setName(simpleName);
я не могу заменить classOrInterfaceType3, потому что у него нет score.

2019-08-09 21:15 UTC, arksap2002 commented on src/test/resources/OnlyTypeChanging.before.java
> +
![image](https://user-images.githubusercontent.com/47223481/62809578-fae33100-bb03-11e9-948a-aaad96d17de3.png)
не могу :(

2019-08-09 21:16 UTC, arksap2002 commented on src/test/resources/OnlyTypeChanging.before.java
> +
он сам их добавляет, сравнивает и говорит, что все плохо

2019-08-11 20:04 UTC, yeputons requested changes

2019-08-11 20:04 UTC, yeputons commented on src/main/java/BigIntegerReplace.java
> +                                    simpleName.asString());
Странно создавать `simpleName`, чтобы потом сразу превратить его в строчку. Передавай сразу строчку. Избавишься от переменной.

2019-08-11 20:04 UTC, yeputons commented on src/main/java/BigIntegerReplace.java
> +                    classOrInterfaceType3.setName(simpleName);
У него нет scope, но есть имя - там вроде есть конструктор чисто по имени.

2019-08-11 20:04 UTC, yeputons commented on src/test/java/BigIntegerReplaceTest.java
> +        assertEquals(IOUtils.resourceToString(filePrefix + ".after.java", Charset.defaultCharset()), gotOutput);
Отлично

2019-08-11 20:04 UTC, yeputons commented on src/test/resources/ReplaceVariableDeclarationType.before.java
> +
Пустые строчки лесом. Название должно совпадать с именем файла максимально (т.е. вся часть до `.before.java`).

2019-08-12 10:34 UTC, yeputons requested changes

2019-08-12 10:34 UTC, yeputons commented on src/main/java/BigIntegerReplace.java
> +                    ClassOrInterfaceType classOrInterfaceType1 =
Избавься от  этих переменных, они не нужны и в отрыве друг от друга бесполезны. Можно написать одно выражение.

2019-08-12 10:34 UTC, yeputons commented on src/test/resources/ReplaceVariableDeclarationType.after.java
> +    java.math.BigInteger a, k, l, m, n = 10;
Это не компилируется, а тесты хорошо бы иметь корректными

2019-08-12 10:34 UTC, yeputons commented on src/test/resources/ReplaceVariableDeclarationType.after.java
> +        java.math.BigInteger f = 15;
Аналогично тут

2019-08-12 11:20 UTC, yeputons requested changes

2019-08-12 11:20 UTC, yeputons commented on src/test/resources/ReplaceVariableDeclarationType.after.java
> +    java.math.BigInteger a = 1, k = 2, l = 5, m = 100, n = 10;
Это всё ещё не компилируется. Убедись, что все тестовые файлы компилируются. Потом добавим автоматический тест.

2019-08-14 16:48 UTC, yeputons approved these changes

2019-08-14 17:02 UTC, merged