Plan
arksap2002/int-increase pull request #21
Opened 2019-09-12 10:53 UTC by arksap2002

2019-09-13 19:19 UTC, yeputons requested changes

2019-09-13 19:19 UTC, yeputons commented on src/main/java/BigIntegerReplace.java
> +        (new Replacing()).doReplace(compilationUnit,
Скобочки вокруг `new ...` не нужны

2019-09-13 19:19 UTC, yeputons commented on src/main/java/Replacing.java
> +    final void doReplace(final CompilationUnit compilationUnit,
Сделать приватным, запускать только из одного специально выделенного статического метода, который заодно создаёт `Replacing`

2019-09-13 19:19 UTC, yeputons commented on src/main/java/Replacing.java
> +            expressionsChanging(expression);
Всё ещё анализирует дерево. Надо тоже распилить на две части

2019-09-13 19:19 UTC, yeputons commented on src/main/java/Replacing.java
> +                    if (flag) {
Возьмите `Set<Expression> = new HashSet<>()` и не парься о дубликатах

2019-09-16 18:29 UTC, arksap2002 commented
Делать ответвления от этого PR. Забить и закрыть остальные с устаревшей структурой.

2019-09-16 19:23 UTC, yeputons requested changes

2019-09-16 19:23 UTC, yeputons commented on src/main/java/BigIntegerReplace.java
> +final class BigIntegerReplace {
Такие изменения лучше выносить в отдельный PR. А конкретно тут лучше оставить `public`.

2019-09-16 19:23 UTC, yeputons commented on src/test/java/BigIntegerReplaceTest.java
> +    public void testScannerWithClass() throws IOException, ClassNotFoundException {
От этих изменений избавиться

2019-09-16 19:23 UTC, yeputons commented on src/main/java/Replacing.java
> +                    variableDeclaratorsAfter.add(makingAfter(
1. Массивы `variableDeclaratorsBefore` и `variableDeclaratorsAfter` рассинхронизированы. Лучше сделать один массив из объектов.
2. Генерация объекта "на который заменяем" должна быть на этапе замены. Чтобы учитывать, что дети могли измениться.

2019-09-16 19:23 UTC, yeputons commented on src/main/java/Replacing.java
> +                n.asMethodCallExpr().setName(new SimpleName("nextBigInteger"));
Тут лучше тоже сделать отдельный массив `List<MethodCallExpr> scannerNextIntToReplace`.

2019-09-16 19:28 UTC, yeputons requested changes
Глобальное изменение: заводим один массив с действиями "измени дерево" (массив `Runnable`). Это идеально разделит просмотр дерева и изменения кода.

2019-09-20 19:08 UTC, yeputons commented on src/main/java/Replacing.java
> +                        n.setInitializer(makingAfter(n.getInitializer().get()));
`n.getInitializer()` и `if` строчкой выше тоже стоит делать вне `Runnable`

2019-09-23 17:04 UTC, arksap2002 commented on src/main/java/Replacing.java
> +                        n.setInitializer(makingAfter(n.getInitializer().get()));
не думаю, что это стоит, потому что если Initializer не существует, то все равно нужно менять на bigInt. Пример: int a = 71

2019-09-25 19:36 UTC, yeputons approved these changes

2019-09-25 19:39 UTC, merged