Signum
arksap2002/int-increase pull request #30
Opened 2019-10-13 11:19 UTC by arksap2002

2019-10-14 19:15 UTC, yeputons requested changes

2019-10-14 19:15 UTC, yeputons commented on src/main/java/Replacing.java
> +                        n.asMethodCallExpr().getName())));
Лучше не `getName()`, а явно записать `"signum"`

2019-10-16 19:46 UTC, yeputons approved these changes

2019-10-16 19:48 UTC, yeputons requested changes
Хорошее замечание от @arksap2002 : `signum` возвращает `int`. Так что его может быть надо завернуть в `valueOf()`

2019-11-29 17:30 UTC, arksap2002 commented
После мержа кучи веток

2020-01-15 22:58 UTC, closed without merging