OtherTypeValues
arksap2002/int-increase pull request #37
Opened 2019-10-14 19:07 UTC by arksap2002

2019-10-14 19:22 UTC, yeputons requested changes

2019-10-14 19:22 UTC, yeputons commented on src/main/java/Replacing.java
> +                        && resolvedN.getClassName().equals("Integer")
`getQualifiedName`

2019-10-14 19:22 UTC, yeputons commented on src/main/java/Replacing.java
> +                        asMethodCallExpr().getScope().isPresent()) {
Это скорее должен быть общий разбор для вообще всех возможных `methodCall`, причём не просто на один уровень вниз, а на сколько угодно.

2019-10-15 18:48 UTC, arksap2002 commented
Это задание не выполнить, пока не сделан выбор интов пользователем, потому что в зависимости то типа инта внутри будет разный код :-(

2019-11-15 11:49 UTC, arksap2002 commented on src/main/java/Replacing.java
> +                    changes.add(() -> n.setScope(n.clone().getScope().get().asMethodCallExpr().getArgument(0)));
-я могу только такой костыль вставить. Не могу дотянуться до элемента внутри :(

2019-11-29 17:30 UTC, arksap2002 commented
После мержа кучи веток
или закрыть и добивить в обобщения

2020-01-15 22:58 UTC, closed without merging