Comment
arksap2002/int-increase pull request #41
Opened 2019-10-19 22:07 UTC by arksap2002

2019-10-21 19:59 UTC, arksap2002 commented
После мержа For все пройдет :)

2019-10-28 19:45 UTC, yeputons requested changes
В тестах стоит пометить вообще __все__ переменные как `BigInteger`. Чтобы не проверять глазами, что новое поведение теста корректно.

А дальше создать отдельно несколько тестов, где есть переменные, не помеченные `BigInteger`.

2019-10-28 19:45 UTC, yeputons commented on src/main/java/Replacing.java
> +                    && (!isInVariableDeclarators(n.asNameExpr())))) {
Лишние скобочки

2019-10-28 19:45 UTC, yeputons commented on src/main/java/Replacing.java
> +            if (!isOfTypeInt(n) || (isOfTypeInt(n)
Кажется, что тут достаточно проверить `!isInVariableDeclarators`. Потому что если `!isOfTypeInt`, то точно `!isInVariableDeclarators`.
И хотим-то мы именно это: мы хотим специально обработать переменные, которые не заменяем на BigInteger. Вдруг захотим `double` ещё заменять?

2019-10-28 19:45 UTC, yeputons commented on src/main/java/Replacing.java
> +            return false;
Лучше ставить не тут один раз, а в каждой ветке отдельно. Тогда будет явная цепочка `if ... else if ... else if ... else return false`, а не `if ... else if ... else if ... /* тут ещё 100500 строк, уже забыли, в каком случае не поставлен else */ return false`

2019-10-28 19:45 UTC, yeputons commented on src/main/java/Replacing.java
> +            if (n.getType().equals(PrimitiveType.intType())
Аналогично, должно быть достаточно проверить `range`.

2019-10-28 19:45 UTC, yeputons commented on src/main/java/Replacing.java
> +            if (isOfTypeInt(n.getTarget())
Аналогично, должно быть достаточно проверить `isInVariableDeclarators`.

2019-10-28 19:45 UTC, yeputons commented on src/main/java/Replacing.java
> +                        getContent().equals(" BigInteger ")
Лучше вызвать `.trim()` у строчки. И `.toLowerCase()` заодно. И это всё в #39.

2019-11-02 07:31 UTC, yeputons requested changes
Основная претензия — к старым тестам.

Они должны __минимально__ изменяться. В идеале `.after` вообще меняться не должен. А если и поменялся — то лишь потому что какие-то старые выражения перестали меняться (которые не содержат BigInteger, а содержат лишь интовые константы).

Все остальные случаи надо внимательно прочитать.

2019-11-02 07:31 UTC, yeputons commented on src/main/java/Replacing.java
> +            return false;
Всё ещё актуально. Этого `return` быть не должно.

2019-11-02 07:31 UTC, yeputons commented on src/main/java/Replacing.java
> +                    && isChange(n.getTarget().asNameExpr())) {
Не сошлось. Если слева стоит `BigInteger`, то мы __обязаны__ заменить выражение, иначе не скомпилируется. Добавь на это тест

2019-11-02 07:31 UTC, yeputons commented on src/main/java/Replacing.java
> +                    System.out.println(declarator.getOrphanComments().get(0).
Отладочный вывод, лесом

2019-11-02 07:31 UTC, yeputons commented on src/test/resources/AssingExpr.after.java
> +        java.math.BigInteger c, d = java.math.BigInteger.ONE;
Файлы `.after` меняться не должны в этом PR, если нет веской причины.

2019-11-02 07:31 UTC, yeputons commented on src/test/resources/ForWhile.after.java
> +        while (i.compareTo(java.math.BigInteger.valueOf(100)) < 0) {
Файлы `.after` сильно меняться не должны в этом PR, если нет веской причины.

2019-11-02 07:31 UTC, yeputons commented on src/test/resources/MathFromImport.after.java
> +    java.math.BigInteger k = java.math.BigInteger.valueOf(a).max(java.math.BigInteger.valueOf(c)).min(java.math.BigInteger.valueOf(c).max(java.math.BigInteger.valueOf(d)).abs()).abs();
Не сошлось, `a` и так уже `BigInteger`

2019-11-02 07:31 UTC, yeputons commented on src/test/resources/MathWithClass.after.java
> +        System.out.println(java.lang.Math.max(java.lang.Math.abs(10), 90));
Не должно быть сильных изменений без серьёзной причины.

2019-11-02 07:31 UTC, yeputons commented on src/test/resources/ScannerFromImport.after.java
> +        java.math.BigInteger a = scanner.nextBigInteger();
Не должно быть сильных изменений без серьёзной причины.

2019-11-02 07:36 UTC, yeputons commented on src/test/resources/If.before.java
> +        if (b > 10) {
Должны __только__ добавляться `/* BigInteger */`

2019-11-03 17:56 UTC, arksap2002 commented on src/main/java/Replacing.java
> +            return false;
Мне кажется, что стоит оставить return, поттому что иначе программа будет падать на таких конструкциях, как:
int a = 0;
pw = new pw
sc = new sc
sout(1)

2019-11-03 18:18 UTC, arksap2002 commented on src/main/java/Replacing.java
> +                    && isChange(n.getTarget().asNameExpr())) {
Если проблема тут:
if (!n.getOperator().equals(AssignExpr.Operator.ASSIGN)) {
то это тогда, если оператор = AssignExpr.Operator.ASSIGN, то все хорошо, потому что мы уже все поменяли (равно везде одинаковое)
Если проблема в том, что заменяю только инты, то если там стоит BigInteger, то тогда у нас некорректный код, потому что переменные меняются только в конце

2019-11-03 18:21 UTC, arksap2002 commented on src/main/java/Replacing.java
> +                    System.out.println(declarator.getOrphanComments().get(0).
я хотел на созвоне обсудить этот момент, но забыл( Я оставил, как напоминалку, потому что ситуацию int a; я не умею обрабатывать( . Там другой вид коммента

2019-11-03 18:37 UTC, arksap2002 commented on src/test/resources/MathWithClass.after.java
> +        System.out.println(java.lang.Math.max(java.lang.Math.abs(10), 90));
но ведь изменения комментов вляиет на код

2019-11-03 18:39 UTC, arksap2002 commented on src/test/resources/If.before.java
> +        if (b > 10) {
я добавил, чтобы было видно разницу

2019-11-06 07:30 UTC, yeputons requested changes
Если хочется всё-таки менять старые тесты, то это надо вынести в отдельный Pull Request. А в этом изменения тестов должны быть чисто механические, не интеллектуальные. Интеллектуальные будем изучать отдельно.

2019-11-06 07:30 UTC, yeputons commented on src/main/java/Replacing.java
> +    private boolean isInVariableDeclarators(final NameExpr n) {
`isVariableToReplace`

2019-11-06 07:30 UTC, yeputons commented on src/main/java/Replacing.java
> +            return false;
Их нормально не рассматривать отдельно, но они же вроде в этой функции не рассматриваются вообще и спокойно себе пойдут в финальную ветку `else`..?
```
if (...) {
  ...
} else if (...) {
  ...
} else
  return false;
```

2019-11-06 07:30 UTC, yeputons commented on src/main/java/Replacing.java
> +                    && isChange(n.getTarget().asNameExpr())) {
Не, проблема, именно в подсвеченной строчке. Например:

```
int /* BigInteger */ a = 0;
a += 5;
```

Тут справа число, но мы обязаны всё заменить.

2019-11-06 07:30 UTC, yeputons commented on src/test/java/BigIntegerReplaceTest.java
> +        runTestFromFile("Comment");
Тестируются не комментарии, а частичная замена. Лучше `testPartialReplace` или что-то такое.

2019-11-06 07:30 UTC, yeputons commented on src/test/resources/AssingExpr.after.java
> +        java.math.BigInteger c, d = java.math.BigInteger.ONE;
Всё ещё актуально.

2019-11-06 07:30 UTC, yeputons commented on src/test/resources/Comment.after.java
> +public class Comment {
Большеват тест. Стоит распилить на несколько независимых с разными названиями, каждый из которых тестирует что-то одно.

2019-11-06 07:30 UTC, yeputons commented on src/test/resources/ForWhile.after.java
> +        while (i.compareTo(java.math.BigInteger.valueOf(100)) < 0) {
Всё ещё актуально.

2019-11-06 07:30 UTC, yeputons commented on src/test/resources/If.after.java
> +        java.math.BigInteger b = java.math.BigInteger.ZERO;
Файлы `.after.java` не должны меняться без веской причины.

2019-11-06 07:30 UTC, yeputons commented on src/test/resources/If.before.java
> +        if (b > 10) {
Между старым и новым поведением же тут разницы нет - всегда заменить всё на `BigInteger`?

2019-11-06 07:30 UTC, yeputons commented on src/test/resources/MathWithClass.after.java
> +        System.out.println(java.lang.Math.max(java.lang.Math.abs(10), 90));
Тут добавилась лишняя строчка в тест зачем-то.

2019-11-06 07:30 UTC, yeputons commented on src/test/resources/ParseInt.after.java
> +        integer = new java.math.BigInteger(number).multiply(new java.math.BigInteger(number));
Не должно быть изменений в `.after.java` без веской причины.

2019-11-06 07:30 UTC, yeputons commented on src/test/resources/ScannerFromImport.after.java
> +        java.math.BigInteger a = scanner.nextBigInteger();
Всё ещё актуально

2019-11-06 16:17 UTC, arksap2002 commented on src/main/java/Replacing.java
> +            return false;
у меня такой ветки нет. У меня просто return false;. Вообще она не очень и нужна, ведь раз уж мы дошли до туда, то true уже не будет.

2019-11-06 16:23 UTC, arksap2002 commented on src/main/java/Replacing.java
> +                    && isChange(n.getTarget().asNameExpr())) {
у меня есть такой тест. Все работает.
public class Brief {
    public static void main(String[] args) {
        int /* BigInteger */ a = 0;
        a++;
        a--;
        a += 10;
        a -= -1;
        a /= 2;
        a %= 3;
        a = 100;
    }
}

2019-11-06 16:24 UTC, arksap2002 commented on src/test/resources/If.before.java
> +        if (b > 10) {
я хотел друг с другом сравнивать

2019-11-06 19:26 UTC, yeputons requested changes
Надо обязательно разделить `PartialChange` на отдельные независимые тесты, невозможно глазами проверить 50 строк на корректность
Например: только присваивания, только арифметика, только циклы, только `if`...

2019-11-06 19:26 UTC, yeputons commented on src/main/java/Replacing.java
> +            for (int i = 0; i < fieldDeclaration.getVariables().size(); i++) {
У нас на входе уже была переменная. Очень странно, что тут ты проверяешь все переменные внутри `fieldDelcaration`, зачем?

2019-11-06 19:26 UTC, yeputons commented on src/main/java/Replacing.java
> +        return false;
Аналогично: не должно быть никакой последней операции этот `return` должен быть в ветке `else`

2019-11-06 19:26 UTC, yeputons commented on src/main/java/Replacing.java
> +//            throw new UnsupportedOperationException();
Комментарий лучше убрать

2019-11-06 19:52 UTC, yeputons requested changes

2019-11-06 19:52 UTC, yeputons commented on src/test/resources/PartialReplaceIf.before.java
> +        int /* BigInteger */ a = 2 + 9 + 12 * 8 - 200 / 100;
Выпилить сложное выражение, оно уже проверено в арифметике.

2019-11-06 19:52 UTC, yeputons commented on src/test/resources/PartialReplacePrintAndParseInt.before.java
> +        int /* BigInteger */ a = 2 + 9 + 12 * 8 - 200 / 100;
Выпилить сложное выражение, оно уже проверено в арифметике.

2019-11-06 19:52 UTC, yeputons commented on src/test/resources/PartialReplacePrintAndParseInt.before.java
> +        String number1 = "11";
Эти переменные вроде не нужны, можно сразу передать в `parseInt` строчку.

2019-11-06 19:52 UTC, yeputons commented on src/test/resources/PartialReplacePrintAndParseInt.before.java
> +        java.io.PrintWriter printWriter = new java.io.PrintWriter("output.out");
Тут стоит делать try-with-resources.

2019-11-06 19:52 UTC, yeputons commented on src/test/resources/PartialReplacePrintAndParseInt.before.java
> +        int g;
Эти две переменные не используются, лесом или в другой тест, попроще.

2019-11-06 19:52 UTC, yeputons commented on src/test/resources/PartialReplacePrintAndParseInt.before.java
> +public class PartialReplacePrintAndParseInt {
Разделить на `PrintInt`/`ParseInt`.

2019-11-08 18:43 UTC, arksap2002 commented on src/test/resources/PartialReplacePrintAndParseInt.before.java
> +        int g;
они нужны, чтобы понять, меняется ли "int" на "java.math.BigInteger"

2019-11-08 19:22 UTC, yeputons approved these changes

2019-11-08 19:22 UTC, yeputons commented on src/test/resources/PartialReplaceIf.before.java
> +}
Не хватает пустой строчки в конце файла

2019-11-08 19:45 UTC, merged