NumericLiteralChanging
arksap2002/int-increase pull request #5
Opened 2019-08-13 21:21 UTC by arksap2002

2019-08-22 19:28 UTC, yeputons requested changes

2019-08-22 19:28 UTC, yeputons commented on src/main/java/BigIntegerReplace.java
> +            if (isInt(n) || isBigInteger(n)) {
Оставить только один случай. Возможно, перенести проверку условия перед `super.visit`

2019-08-22 19:28 UTC, yeputons commented on src/main/java/BigIntegerReplace.java
> +        private void changingInitializerOfVariableDeclarator(
`changing` --> `replace`/`change`, тут и везде

2019-08-22 19:28 UTC, yeputons commented on src/main/java/BigIntegerReplace.java
> +            if (n.isBinaryExpr()) {
Тут и дальше - `else if`

2019-08-22 19:28 UTC, yeputons commented on src/main/java/BigIntegerReplace.java
> +                 binExpr.setOperator(BinaryExpr.Operator.MULTIPLY);
Тут лучше заменять не на `BinaryExpr`, а на `.negate()`, но при этом не надо добавлять обработку `MethodCall`

2019-08-22 19:28 UTC, yeputons commented on src/main/java/BigIntegerReplace.java
> +        private Expression initializerIntegerLiteralExpr(
`initializer` --> `create`

2019-08-26 09:31 UTC, yeputons requested changes

2019-08-26 09:31 UTC, yeputons commented on src/main/java/BigIntegerReplace.java
> +            }
Добавь ветку эльсе, которая кидает исключение (`RuntimeException`). Иначе получится замалчивание потенциальной ошибки.

2019-08-26 09:31 UTC, yeputons commented on src/main/java/BigIntegerReplace.java
> +            if (number == 1) {
`else if`

2019-08-26 09:31 UTC, yeputons commented on src/main/java/BigIntegerReplace.java
> +            methodCallExpr.setArguments(new NodeList<>(
Есть конструктор, который позволяет сделать то же самое в один вызов, используй его. Аналогично во вскех остальных местах: убедись, что код нельзя упростить.

2019-08-26 09:31 UTC, yeputons commented on src/main/java/BigIntegerReplace.java
> +                    asPrimitiveType().equals(PrimitiveType.intType());
В случае с конкретно `equals()` можно убрать `asPrimitiveType()` и не писать проверку `isPrimitiveType()`

2019-08-26 15:52 UTC, yeputons requested changes

2019-08-26 15:52 UTC, yeputons commented on src/main/java/BigIntegerReplace.java
> +            }
?

2019-08-26 15:52 UTC, yeputons commented on src/main/java/BigIntegerReplace.java
> +                        new NameExpr("BigInteger"), "ZERO");
Подозрительно, что тут не указан пакет для класса. Добавь тест, что это не до конца верное решение .

2019-08-26 15:52 UTC, yeputons commented on checkstyle.xml
> +
Лишняя пустая строчка

2019-08-27 10:41 UTC, arksap2002 commented on src/main/java/BigIntegerReplace.java
> +            }
Аналогично примеру из https://javarush.ru/groups/posts/1944-iskljuchenija-checked-unchecked-i-svoi-sobstvennihe

2019-08-27 10:45 UTC, arksap2002 commented on src/main/java/BigIntegerReplace.java
> +            }
и он падает, так как есть NameExpr

2019-08-29 20:12 UTC, yeputons requested changes
И тут надо будет сделать `git rebase -i master` после #3

Цель: чтобы в этом PR были только новые измемения: замена числовых литералов на `BigInteger.*`

2019-08-29 20:12 UTC, yeputons commented on src/main/java/BigIntegerReplace.java
> +                    } catch (UnhandledObjectException e) {
Тут лучше упростить: не надо ловить исключение (всё равно  его никак разумно не обработать, а сообщение об ошибке и так будет выведено)

2019-08-29 20:12 UTC, yeputons commented on src/main/java/BigIntegerReplace.java
> +                        e.printStackTrace();
Тем более что тут программа молча продолжает работу, хотя контракт уже нарушен: в коде есть что-то непонятное

2019-08-29 20:12 UTC, yeputons commented on src/main/java/BigIntegerReplace.java
> +                throw new UnhandledObjectException("Object " + n.toString()
Лучше стандартный `NotImplementedException`

2019-08-30 19:54 UTC, merged