UnaryChange
arksap2002/int-increase pull request #6
Opened 2019-08-22 23:05 UTC by arksap2002

2019-08-22 23:10 UTC, arksap2002 commented
https://static.javadoc.io/com.github.javaparser/javaparser-core/3.5.0/com/github/javaparser/ast/expr/UnaryExpr.Operator.html

2019-08-26 19:13 UTC, arksap2002 commented
@yeputons

2019-08-29 20:14 UTC, yeputons requested changes
Тут тоже нужен `rebase`.

2019-08-29 20:14 UTC, yeputons commented on src/test/resources/UnaryChange.before.java
> +        int b = -5 - 2 / 67 + 1 * (-1) / (+100);
Добавь унарный минус перед какими-нибудь скобками

2019-08-29 20:16 UTC, yeputons commented on src/main/java/BigIntegerReplace.java
> +                }
`else` — `NotImplementedException`

2019-08-30 20:26 UTC, closed without merging